approvedGitRepositories:
  - "**"
npmPreapprovedPackages:
  - agile-form
  - application-server-web-node-plugin
  - archinstall
  - backup-rotation
  - bashlink
  - clientnode
  - containerbase
  - couchdb-web-node-plugin
  - ejs-web-node-plugin
  - errorreporter
  - legal-notes
  - maintainancewebsite
  - nginxwebnodeplugin
  - polyfill-bundler
  - prerenderwebnodeplugin
  - proxy
  - reachable-watcher
  - react-generic-animate
  - react-generic-dummy
  - react-generic-tools
  - react-input-material
  - reverse-proxy-middleware
  - web-component-wrapper
  - web-documentation
  - web-input-material
  - web-internationalization
  - web-node
  - weboptimizer
  - website
  - website-utilities

enableScripts: true

nodeLinker: node-modules
